// Generated by npm run build. Edit src/client.js.
window.__ModuleLoader__.load({id:"@canary-builds/dsh-connect",factory:(require)=>{
// Factory body compiled by scripts/build.mjs. No Node imports or browser bundler.
const React = require('react');
const h = React.createElement;
const inject = ['slots'];
const styles = {
  root: { maxWidth: 820, display: 'flex', flexDirection: 'column', gap: 20, color: 'var(--dsw-alias-label-primary)' },
  card: { padding: 20, border: '1px solid var(--dsw-alias-border-l2)', borderRadius: 12, background: 'var(--dsw-alias-bg-layer-3)' },
  row: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 12 },
  muted: { color: 'var(--dsw-alias-label-secondary)', lineHeight: 1.6 },
  button: { border: '1px solid var(--dsw-alias-border-l2)', borderRadius: 8, padding: '8px 14px', background: 'var(--dsw-alias-bg-layer-1)', color: 'inherit', cursor: 'pointer' },
  table: { width: '100%', borderCollapse: 'collapse', textAlign: 'left', lineHeight: 2.1 },
  code: { fontFamily: 'monospace', fontSize: 12, overflowWrap: 'anywhere' },
  footer: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, fontSize: 12, borderTop: '1px solid var(--dsw-alias-border-l2)', paddingTop: 12 },
  link: { color: 'var(--dsw-alias-label-secondary)', textUnderlineOffset: 3 },
  issue: { color: 'var(--dsw-alias-state-error-primary, #c44)', lineHeight: 1.5 },
};
async function request(path = '', method = 'GET', signal) {
  const response = await fetch('/api/dsh-connect' + path, { method, credentials: 'same-origin', headers: { accept: 'application/json' }, signal });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || 'DSH Connect is unavailable.');
  return body;
}
function CodexSettings() {
  const [state, setState] = React.useState(null);
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState('');
  const [waiting, setWaiting] = React.useState(false);
  const [authUrl, setAuthUrl] = React.useState('');
  const [waitingGrok, setWaitingGrok] = React.useState(false);
  const [grokUrl, setGrokUrl] = React.useState('');
  const [grokCode, setGrokCode] = React.useState('');
  const load = React.useCallback(async signal => {
    const next = await request('', 'GET', signal);
    setState(next);
    if (next.authenticated) { setWaiting(false); setAuthUrl(''); }
    if (next.grok?.authenticated) { setWaitingGrok(false); setGrokUrl(''); setGrokCode(''); }
    return next;
  }, []);
  React.useEffect(() => {
    const controller = new AbortController();
    load(controller.signal).catch(e => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [load]);
  React.useEffect(() => {
    if (!waiting && !waitingGrok) return;
    const controller = new AbortController();
    let timer;
    const poll = async () => {
      try { await load(controller.signal); }
      catch (e) { if (!controller.signal.aborted) setError(e.message); }
      if (!controller.signal.aborted) timer = setTimeout(poll, 2000);
    };
    timer = setTimeout(poll, 2000);
    const expiry = setTimeout(() => { setWaiting(false); setAuthUrl(''); setWaitingGrok(false); setGrokUrl(''); setGrokCode(''); setError('Sign-in timed out. Check the SSH tunnel and start again.'); }, 5 * 60_000);
    return () => { controller.abort(); clearTimeout(timer); clearTimeout(expiry); };
  }, [waiting, waitingGrok, load]);
  async function act(path) {
    setBusy(true); setError('');
    const signingIn = path === '/login' || path === '/grok/login';
    const popup = signingIn ? window.open('about:blank', '_blank') : null;
    if (popup) popup.opener = null;
    try {
      const result = await request(path, 'POST');
      if (path === '/login') {
        setAuthUrl(result.authUrl); setWaiting(true);
        if (popup) popup.location.href = result.authUrl;
      } else if (path === '/grok/login') {
        setGrokUrl(result.authUrl); setGrokCode(result.userCode || ''); setWaitingGrok(true);
        if (popup) popup.location.href = result.authUrl;
      } else { setState(path === '/refresh' ? result : await load()); }
    } catch (e) { popup?.close(); setError(e.message); }
    finally { setBusy(false); }
  }
  const button = (label, action, extra = {}) => h('button', { type: 'button', style: styles.button, disabled: busy, onClick: action, ...extra }, label);
  const grok = state?.grok;
  const modelRows = [
    ...(state?.models ?? []).map(model => ({ ...model, provider: 'ChatGPT' })),
    ...(grok?.models ?? []).map(model => ({ ...model, provider: 'Grok' })),
  ];
  return h('section', { style: styles.root },
    h('div', null, h('h2', { style: { marginBottom: 8 } }, 'DSH Connect'), h('p', { style: styles.muted }, 'Connect ChatGPT, Grok, or both. Pick either model from the model list.')),
    h('div', { style: styles.card },
      h('div', { style: styles.row, role: 'status', 'aria-live': 'polite' },
        h('strong', null, state ? state.installed === false ? 'ChatGPT not installed' : state.authenticated ? 'ChatGPT connected' : state.connectionIssue ? 'ChatGPT unavailable' : 'ChatGPT sign-in required' : 'Checking connection…'),
        state?.planType ? h('span', { style: styles.muted }, state.planType) : null),
      state ? h('p', { style: styles.muted }, `Plugin ${state.pluginVersion} · ${state.codexVersion}`) : null,
      h('div', { style: styles.row },
        state?.installed === false ? null : state?.authenticated ? button('Sign out of ChatGPT', () => act('/logout')) : button(waiting ? 'Waiting for ChatGPT…' : 'Sign in with ChatGPT', () => act('/login'), { disabled: busy || waiting }),
        button('Refresh connection & models', () => act('/refresh')),
        waiting ? button('Stop waiting', () => { setWaiting(false); setAuthUrl(''); }) : null),
      authUrl ? h('p', null, h('a', { href: authUrl, target: '_blank', rel: 'noopener noreferrer' }, 'Continue ChatGPT sign-in')) : null,
      error || state?.connectionIssue ? h('p', { style: styles.issue, role: 'alert' }, error || state.connectionIssue) : null),
    h('div', { style: styles.card },
      h('div', { style: styles.row },
        h('strong', null, grok ? grok.authenticated ? 'Grok connected' : grok.connectionIssue ? 'Grok unavailable' : 'Grok sign-in required' : 'Grok is not configured')),
      grok ? h('p', { style: styles.muted }, grok.grokVersion) : null,
      h('div', { style: styles.row },
        grok?.authenticated ? button('Sign out of Grok', () => act('/grok/logout')) : button(waitingGrok ? 'Waiting for Grok…' : 'Sign in with Grok', () => act('/grok/login'), { disabled: busy || waitingGrok || !grok }),
        waitingGrok ? button('Stop waiting', () => { setWaitingGrok(false); setGrokUrl(''); setGrokCode(''); }) : null),
      grokUrl ? h('p', null, h('a', { href: grokUrl, target: '_blank', rel: 'noopener noreferrer' }, 'Continue Grok sign-in'), grokCode ? h('span', { style: styles.code }, ` Code ${grokCode}`) : null) : null,
      grok?.connectionIssue ? h('p', { style: styles.issue, role: 'alert' }, grok.connectionIssue) : null),
    state && state.installed !== false && !state.authenticated ? h('div', { style: styles.card },
      h('strong', null, 'Signing in from another computer'),
      h('p', { style: styles.muted }, 'Keep this SSH tunnel open on the computer running your browser until ChatGPT sign-in finishes. 3080 is the usual web port. 1455 is the ChatGPT callback on that computer. Forwarding only the web port leaves the popup unable to finish. Grok device login does not need port 1455.'),
      h('code', { style: styles.code }, 'ssh -N -o ExitOnForwardFailure=yes -L 3080:127.0.0.1:3080 -L 1455:127.0.0.1:1455 user@harness-host')) : null,
    h('div', { style: styles.card },
      h('h3', { style: { marginTop: 0 } }, 'Models'),
      h('p', { style: styles.muted }, state ? `ChatGPT source: ${state.modelSource}. Grok source: ${grok?.modelSource ?? 'unavailable'}. Account access is checked when you send a message.` : 'Loading model catalog…'),
      state?.discoveryIssue ? h('p', { style: styles.muted }, state.discoveryIssue) : null,
      grok?.discoveryIssue ? h('p', { style: styles.muted }, grok.discoveryIssue) : null,
      h('table', { style: styles.table }, h('thead', null, h('tr', null, h('th', null, 'Provider'), h('th', null, 'Model'), h('th', null, 'Model ID'))), h('tbody', null,
        ...modelRows.map(model => h('tr', { key: model.provider + model.id }, h('td', null, model.provider), h('td', null, model.name), h('td', { style: styles.code }, model.id)))))),
    h('p', { style: styles.muted }, 'Supports text, reasoning, and Harness tool calls. Image attachments are not supported by this provider yet. ChatGPT uses the Codex app-server. Grok uses the official Grok CLI.'),
    h('footer', { style: styles.footer },
      h('a', { href: 'https://github.com/Canary-Builds/dhs-connect/issues', target: '_blank', rel: 'noopener noreferrer', style: styles.link }, 'Report an issue'),
      h('a', { href: 'https://canarybuilds.com', target: '_blank', rel: 'noopener noreferrer', style: { ...styles.link, marginLeft: 'auto' } }, 'Canary Builds'))
  );
}
function apply(ctx) {
  ctx.slots.inject('settings.section', () => ctx.slots.register({ name: 'settings.section', id: 'dsh-connect', label: () => 'DSH Connect', order: 11 }, CodexSettings));
}

return { inject, apply, CodexSettings };
}});
