import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { Script } from 'node:vm';
const root = new URL('../', import.meta.url);
const pkg = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
const source = await readFile(new URL('src/client.js', root), 'utf8');
await mkdir(new URL('lib/', root), { recursive: true });
const bundle = `// Generated by npm run build. Edit src/client.js.\nwindow.__ModuleLoader__.load({id:${JSON.stringify(pkg.name)},factory:(require)=>{\n${source}\nreturn { inject, apply, CodexSettings };\n}});\n`;
new Script(bundle, { filename: 'lib/client.js' });
await writeFile(new URL('lib/client.js', root), bundle);
// JSON is valid YAML and safely quotes scoped package names beginning with @.
await writeFile(new URL('cordis.patch.yml', root), JSON.stringify([{ insert: [{ id: 'llm-dsh-connect', name: pkg.name }] }], null, 2) + '\n');
console.error(`Built client registration for ${pkg.name}`);
